name: Process Pull Request

on:
  pull_request:
    types:
      - opened

jobs:
  process-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Mermaid CLI
        run: npm install -g @mermaid-js/mermaid-cli

      - name: Convert Mermaid Markdown to SVG
        run: mmdc -i input.mmd -o output.svg

      - name: Create PR Comment File
        run: echo "![Mermaid Image](output.svg)" > pr_description.txt

      - name: Update PR Description
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          COMMENT=$(cat pr_description.txt)
          URL="https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$PR_NUMBER/comments"
          RESPONSE=$(curl -sSL -H "Authorization: token $GITHUB_TOKEN" -d "{\"body\": \"$COMMENT\"}" -H "Content-Type: application/json" -X POST "$URL")
          echo "PR Comment Response: $RESPONSE"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
